Disable testRunner on Windows due to new issues
I now get this error which I'm not privvy with the knowledge to fix just
yet.

```
FAILED: CMakeFiles/testRunner.util
cmd.exe /C "cd /D C:\Home\Code\trueblocks-core\src && go build -o C:/Home/Code/trueblocks-core/src/../bin/testRunner.exe C:/Home/Code/trueblocks-core/src/dev_tools/testRunner/api_server.go C:/Home/Code/trueblocks-core/src/dev_tools/testRunner/filter.go C:/Home/Code/trueblocks-core/src/dev_tools/testRunner/main.go C:/Home/Code/trueblocks-core/src/dev_tools/testRunner/main_test.go C:/Home/Code/trueblocks-core/src/dev_tools/testRunner/prepare.go C:/Home/Code/trueblocks-core/src/dev_tools/testRunner/run_api.go C:/Home/Code/trueblocks-core/src/dev_tools/testRunner/run_cmd.go C:/Home/Code/trueblocks-core/src/dev_tools/testRunner/run_sdk.go C:/Home/Code/trueblocks-core/src/dev_tools/testRunner/test_case.go C:/Home/Code/trueblocks-core/src/dev_tools/testRunner/test_runner.go"
C:\Users\<user>\go\pkg\mod\github.com\!true!blocks\trueblocks-core\sdk\v3@v3.0.0-20240728020742-8b2832e69983\when_internal.go:86:9: undefined: types.TimestampCount
C:\Users\<user>\go\pkg\mod\github.com\!true!blocks\trueblocks-core\sdk\v3@v3.0.0-20240728020742-8b2832e69983\when.go:59:47: undefined: types.TimestampCount
C:\Users\<user>\go\pkg\mod\github.com\!true!blocks\trueblocks-core\sdk\v3@v3.0.0-20240728020742-8b2832e69983\when.go:62:25: undefined: types.TimestampCount
```